Repository marrow/mailer, pull requests merged in 2020-04, with the labels that each got.

#86 Fix simple typo: produciton -> production
  marrow/mailer/logger.py
Labels: 2.enhancement, need:documentation

#89 Delete `optimize` setting from setup.cfg, as it causes .pyc files to be included in the wheel
  setup.cfg
Labels: 2.enhancement, need:optimization

#88 Exclude `test`, not `tests`
  setup.py
Labels: 2.enhancement, area:packaging
